# Cursor Commands
[providers.cursor.commands]
template = "https://dotagents.soorya-u.dev/v1/templates/cursor/command.hbs"
target = "{{dir.workspace}}/.cursor/commands/{{command.name}}.md"

# Cursor Skills
[providers.cursor.skills]
target = "{{dir.workspace}}/.cursor/skills/{{skill.name}}/SKILL.md"

[providers.cursor.instructions]
template = "https://dotagents.soorya-u.dev/v1/templates/cursor/instruction.hbs"
target = "{{dir.workspace}}/AGENTS.md"

[providers.cursor.mcp]
template = "https://dotagents.soorya-u.dev/v1/templates/cursor/mcp.hbs"
target = "{{dir.workspace}}/.cursor/mcp.json"

[providers.cursor.hooks]
template = "https://dotagents.soorya-u.dev/v1/templates/cursor/hooks.hbs"
target = "{{dir.workspace}}/.cursor/hooks.json"

[providers.cursor.ignore]
target = "{{dir.workspace}}/.cursorignore"
