[package]
name = "dotagents"
version = "0.0.0-rc.1"
authors = ["Soorya U <sooryau7@gmail.com>"]
description = "An agent configuration manager and templater written in rust"
repository = "https://github.com/soorya-u/dotagents"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["dotagents", "configuration", "dotfiles", "agent"]
categories = ["command-line-utilities"]
edition = "2024"

[features]
default = []
skills-add = []

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.48", features = ["derive"] }
clap_complete = "4.5.58"
cliclack = "0.5.4"
console = "0.16.3"
crossterm = "0.29.0"
dirs = "6.0.0"
dotenvy = "0.15.7"
gray_matter = "0.3.2"
handlebars = "6.3.2"
hex = "0.4.3"
home = "0.5.11"
log = "0.4.28"
rayon = "1.11.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
serde_json5 = "0.2.1"
serde_yaml = "0.9.34"
sha2 = "0.11.0"
simplelog = "0.12.2"
smallvec = "1.15.1"
toml = "0.9.8"
ureq = { version = "3.3.0", features = ["rustls"] }

[dev-dependencies]
mockall = "0.13.1"
mockito = "1.7.2"
serde_json = "1.0.145"
tempfile = "3.23.0"

[target.'cfg(windows)'.dependencies]
dunce = "1.0.5"

[target.'cfg(unix)'.dependencies]
libc = "0.2.176"

[profile.release]
strip = true
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
