# Kimi Instructions
[providers.kimi.instructions]
template = "https://dotagents.soorya-u.dev/v1/templates/kimi/instruction.hbs"
target = "{{dir.workspace}}/AGENTS.md"

# Kimi Skills
[providers.kimi.skills]
target = "{{dir.workspace}}/.kimi/skills/{{skill.name}}/SKILL.md"

# Kimi MCP
# [providers.kimi.mcp]
# template = "https://dotagents.soorya-u.dev/v1/templates/kimi/mcp.hbs"
# target = "{{dir.home}}/.kimi/mcp.json"
