[providers.cline.skills]
target = "{{dir.workspace}}/.cline/skills/{{skill.name}}/SKILL.md"

[providers.cline.instructions]
template = "https://dotagents.soorya-u.dev/v1/templates/cline/instruction.hbs"
target = "{{dir.workspace}}/.clinerules/instructions.md"

[providers.cline.ignore]
target = "{{dir.workspace}}/.clineignore"
