# Deep Agents Skills
[providers.deepagents.skills]
target = "{{dir.workspace}}/skills/{{skill.name}}/SKILL.md"

# Deep Agents Instructions
[providers.deepagents.instructions]
template = "https://dotagents.soorya-u.dev/v1/templates/deepagents/instruction.hbs"
target = "{{dir.workspace}}/AGENTS.md"

# Deep Agents MCP
[providers.deepagents.mcp]
template = "https://dotagents.soorya-u.dev/v1/templates/deepagents/mcp.hbs"
target = "{{dir.workspace}}/.mcp.json"
