schema = "https://dotagents.soorya-u.dev/schemas/config.schema.json"
features = [
    "commands",
    "instructions",
    "mcp",
    "skills",
]

targets = ["mycode"]

[providers.mycode.mcp]
template = "{{ dir.application }}/templates/mycode/mcp.hbs"
target = "{{ dir.workspace }}/.mycode/mcp.json"

[providers.mycode.instructions]
template = "{{ dir.application }}/templates/mycode/instructions.hbs"
target = "{{ dir.workspace }}/.mycode/instructions.md"
variables = {agent_name = "Mycode"}

[providers.mycode.commands]
template = "{{ dir.application }}/templates/mycode/command.hbs"
target = "{{ dir.workspace }}/.mycode/commands/{{ command.name }}.md"

[providers.mycode.skills]
template = "{{ dir.application }}/templates/mycode/skill.hbs"
target = "{{ dir.workspace }}/.mycode/skills/{{ skill.name }}/SKILLS.md"
